## Global Historical Climatology Network Dataset
Variables are stored in both rows and columns
This dataset represents the daily weather records for a weather station (MX17004) in Mexico for five months in 2010.

In [1]:
import pandas as pd

In [31]:
data = pd.read_csv('../weather-raw.csv')
data

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,26.4,NaN,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,15.0,NaN,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
data.columns

Index(['id', 'year', 'month', 'element', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6',
       'd7', 'd8', 'd9', 'd10', 'd11', 'd12', 'd13', 'd14', 'd15', 'd16',
       'd17', 'd18', 'd19', 'd20', 'd21', 'd22', 'd23', 'd24', 'd25', 'd26',
       'd27', 'd28', 'd29', 'd30', 'd31'],
      dtype='object')

In [33]:
data.dtypes

id          object
year         int64
month        int64
element     object
d1         float64
d2         float64
d3         float64
d4         float64
d5         float64
d6         float64
d7         float64
d8         float64
d9         float64
d10        float64
d11        float64
d12        float64
d13        float64
d14        float64
d15        float64
d16        float64
d17        float64
d18        float64
d19        float64
d20        float64
d21        float64
d22        float64
d23        float64
d24        float64
d25        float64
d26        float64
d27        float64
d28        float64
d29        float64
d30        float64
d31        float64
dtype: object

In [46]:
# elijiremos columnas que están totalmente vacías
empty_colum = data.isnull().sum()
empty_colum[empty_colum == 22]

d9     22
d12    22
d18    22
d19    22
d20    22
d21    22
d22    22
d24    22
dtype: int64

In [47]:
delete_colum = list(empty_colum[empty_colum == 22].index)
print(delete_colum)

['d9', 'd12', 'd18', 'd19', 'd20', 'd21', 'd22', 'd24']

In [49]:
# aqu+í las eliminamos
data = data.drop(delete_colum, axis =1)
data

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d16,d17,d23,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,31.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,17.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,28.0,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17.5,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,NaN,26.4,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,NaN,15.0,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
# para que no haya valores vacíos, vamos a llenar con valores 'cero'
data = data.fillna(0)
data

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d16,d17,d23,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.8,0.0
1,MX17004,2010,1,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,0.0
2,MX17004,2010,2,tmax,0.0,27.3,24.1,0.0,0.0,0.0,...,0.0,0.0,29.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,MX17004,2010,2,tmin,0.0,14.4,14.4,0.0,0.0,0.0,...,0.0,0.0,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,MX17004,2010,3,tmax,0.0,0.0,0.0,0.0,32.1,0.0,...,31.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,MX17004,2010,3,tmin,0.0,0.0,0.0,0.0,14.2,0.0,...,17.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,MX17004,2010,4,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,36.3,0.0,0.0,0.0,0.0
7,MX17004,2010,4,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.7,0.0,0.0,0.0,0.0
8,MX17004,2010,5,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2,0.0,0.0,0.0,0.0
9,MX17004,2010,5,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,18.2,0.0,0.0,0.0,0.0
10,MX17004,2010,6,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,28.0,0.0,0.0,0.0,0.0,0.0,30.1,0.0,0.0
11,MX17004,2010,6,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,17.5,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0
12,MX17004,2010,7,tmax,0.0,0.0,28.6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,MX17004,2010,7,tmin,0.0,0.0,17.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,MX17004,2010,8,tmax,0.0,0.0,0.0,0.0,29.6,0.0,...,0.0,0.0,26.4,29.7,0.0,0.0,0.0,28.0,0.0,25.4
15,MX17004,2010,8,tmin,0.0,0.0,0.0,0.0,15.8,0.0,...,0.0,0.0,15.0,15.6,0.0,0.0,0.0,15.3,0.0,15.4
16,MX17004,2010,10,tmax,0.0,0.0,0.0,0.0,27.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,31.2,0.0,0.0,0.0
17,MX17004,2010,10,tmin,0.0,0.0,0.0,0.0,14.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0
18,MX17004,2010,11,tmax,0.0,31.3,0.0,27.2,26.3,0.0,...,0.0,0.0,0.0,0.0,28.1,27.7,0.0,0.0,0.0,0.0
19,MX17004,2010,11,tmin,0.0,16.3,0.0,12.0,7.9,0.0,...,0.0,0.0,0.0,0.0,12.1,14.2,0.0,0.0,0.0,0.0
20,MX17004,2010,12,tmax,29.9,0.0,0.0,0.0,0.0,27.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,MX17004,2010,12,tmin,13.8,0.0,0.0,0.0,0.0,10.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:
# obtenemos las columnas ya modificadas, para ocuparla en el pivoteo de columnas
list_col = data.columns[4:]
list_col

Index(['d1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'd10', 'd11', 'd13',
       'd14', 'd15', 'd16', 'd17', 'd23', 'd25', 'd26', 'd27', 'd28', 'd29',
       'd30', 'd31'],
      dtype='object')

In [64]:
# con esta visualización podemos ver la temperatura priorizando por está misma
# a mi parecer es mejor esta visualización
df_by_month= data.pivot(index='month', columns='element',values = list_col)
df_by_month

           d1          d2          d3          d4          d5        ...  \
element  tmax  tmin  tmax  tmin  tmax  tmin  tmax  tmin  tmax  tmin  ...
month                                                                ...
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
2         0.0   0.0  27.3  14.4  24.1  14.4   0.0   0.0   0.0   0.0  ...
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  32.1  14.2  ...
4         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
5         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
6         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
7         0.0   0.0   0.0   0.0  28.6  17.5   0.0   0.0   0.0   0.0  ...
8         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  29.6  15.8  ...
10        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  27.0  14.0  ...
11        0.0   0.0  31.3  16.3   0.0   0.0  27.2  12.0  26.3   7.9  ...
12       29.9  13.8   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...

          d27         d28         d29         d30         d31
element  tmax  tmin  tmax  tmin  tmax  tmin  tmax  tmin  tmax  tmin
month
1         0.0   0.0   0.0   0.0   0.0   0.0  27.8  14.5   0.0   0.0
2         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4        36.3  16.7   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
5        33.2  18.2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
6         0.0   0.0   0.0   0.0  30.1  18.0   0.0   0.0   0.0   0.0
7         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
8         0.0   0.0   0.0   0.0  28.0  15.3   0.0   0.0  25.4  15.4
10        0.0   0.0  31.2  15.0   0.0   0.0   0.0   0.0   0.0   0.0
11       27.7  14.2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
12        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[11 rows x 46 columns]

In [65]:
# con esta visualización podemos ver la temperatura, priorizando por día
df_by_temp= data.pivot(index='element', columns='month',values = list_col)
df_by_temp

          d1                                               ...  d31            \
month     1    2    3    4    5    6    7    8    10   11  ...   2    3    4
element                                                    ...
tmax     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
tmin     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0


month     5    6    7     8    10   11   12
element
tmax     0.0  0.0  0.0  25.4  0.0  0.0  0.0
tmin     0.0  0.0  0.0  15.4  0.0  0.0  0.0

[2 rows x 253 columns]